import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Providers from "./components/Providers";

const cpcFont = localFont({
  src: "/fonts/2005_iannnnnAMD.ttf",
  variable: "--font-cpc",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cpcFont.variable}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          {children}
          </Providers>
      </body>
    </html>
  );
}
